### ISSUE TITLE
wrap types instead of pointers to types?

### ISSUE THREAD

**Issue by nuchi** [markisus/variant_ptr#1]
neat!

could it be modified to wrap types instead of pointers? then I think you could do something like
```c++
#define Hands(F) \
  F(Rock), \
  F(Paper), \
  F(Scissors),

#define STD_UNIQUE(t) std::unique_ptr<t>
#define STD_SHARED(t) std::shared_ptr<t>
#define RAW(t) t*

using variant_unq = variant<Hands(STD_UNIQUE)>;
using variant_shr = variant<Hands(STD_SHARED)>;
using variant_raw = variant<Hands(RAW)>;
// etc
```

**Comment by markisus** [comment]
Yes this is possible and actually that's what `boost::variant` does https://www.boost.org/doc/libs/1_67_0/doc/html/variant.html

The implementation is a template that calculates the max number of bytes over all the child types and it creates a `char[]` field with that number of bytes. In that way it's able to actually store elements of all possible child types listed. I didn't want to add that extra complication, because it kind of mixes in the storage aspect with the dispatch aspect.

Also if the variant worked like you suggest, you could have the raw version just be
```c++
#define RAW(t) t
```

right?

**Comment by nuchi** [comment]
oh I see, that'd be super annoying to also have to count bytes.

you're absolutely right — in my head, `RAW` meant `RAW_PTR`, but the thought didn't make it all the way to the keyboard 😄
